pipelines:
   default:
      - parallel:
         - step:
            name: Build and test
            image: atlassian/default-image:3
            script:
               - apt-get -qq update
               - apt-get -qq -y install gcc g++ cmake libboost-all-dev
               - cmake -Bbuild -Hsrc
               - cmake --build build --target all
               - cmake --build build --target check
         - step:
            name: Lint
            image: markdownlint/markdownlint
            script:
               - mdl .
