pipelines:
   default:
      - parallel:
         - step:
            name: Build and test
            image: alpine:3.16
            script:
               - apk add g++ boost-dev cmake samurai
               - cmake --preset dev-linux
               - cmake --build --preset dev-linux --target install
               - ctest --preset dev-linux
         - step:
            name: Lint Markdown
            image: markdownlint/markdownlint
            script:
               - mdl .
         - step:
            name: Lint Dockerfile
            script:
               - docker run --rm -i hadolint/hadolint < Dockerfile
            services:
               - docker
