image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get -qq update
          - apt-get -qq -y install gcc g++ cmake libboost-all-dev
          - cmake -Bbuild -Hsrc
          - cmake --build build