image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt-get update -qq
          - apt-get -y install gcc g++ cmake
          - cmake -Bbuild -Hsrc
          - cmake --build build